/*
   Given two strings s and t which consist of only lowercase letters.
  String t is generated by random shuffling string s and then add one more letter at a random position.
  Find the letter that was added in t.
  Example:
  Input:
  s = "abcd"
  t = "abcde"
  Output:
  e
  Explanation:
  'e' is the letter that was added.
  1) compare the two strings against each other
  2) identify the character that is present in t, but not in s
  3) return the identified character
 */



const letterAdded = (s, t) => {

    for (let i = 0; i < t.length; i++) {

        if (!s.includes(t[i])) {
            return t.split("").splice(i,1).join("");
        };
    };
};

console.log("abcd, abcde, expected output e: ", letterAdded("abcd", "abcde"))
console.log("crab, brace, expected output e: ", letterAdded("crab", "brace"))
console.log("drink, srinkd, expected output s: ", letterAdded("drink", "drisnk"))
console.log("shrinked, inkaedshr, expected output a: ", letterAdded("shrinked", "inkaedshr"))